[package]
name = "sourceview"
license = "MIT"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["gdk", "gtk", "gtk-rs", "gnome", "GUI"]
readme = "README.md"
documentation = "http://gtk-rs.org/docs/sourceview/"
version = "0.3.0"
description = "Rust bindings for the GtkSourceView 3 library"
repository = "https://github.com/gtk-rs/sourceview"
build = "build.rs"

[lib]
name = "sourceview"

[features]
v3_0 = []
v3_10 = ["v3_0", "gtk-source-sys/v3_10"]
v3_12 = ["v3_10", "gtk-source-sys/v3_12"]
v3_16 = ["v3_12", "gtk-source-sys/v3_16"]
v3_18 = ["v3_16", "gtk-source-sys/v3_18"]
v3_20 = ["v3_18", "gtk-source-sys/v3_20"]
v3_22 = ["v3_20", "gtk-source-sys/v3_22"]
v3_24 = ["v3_22", "gtk-source-sys/v3_24"]
default = ["v3_0"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gio/purge-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gio/embed-lgpl-docs"]
dox = ["gtk/dox", "gtk-source-sys/dox"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"

[dependencies.gtk-source-sys]
version = "0.5.0"
path = "./sourceview-sys"

[dependencies.glib-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gio-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gtk-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gdk-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gdk-pixbuf-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.glib]
version = "0.4.0"
git = "https://github.com/gtk-rs/glib"

[dependencies.pango]
version = "0.3.0"
git = "https://github.com/gtk-rs/pango"

[dependencies.gtk]
version = "0.3.0"
git = "https://github.com/gtk-rs/gtk"

[dependencies.gdk]
version = "0.7.0"
git = "https://github.com/gtk-rs/gdk"

[dependencies.cairo-rs]
version = "0.3.0"
git = "https://github.com/gtk-rs/cairo"

[dependencies.gdk-pixbuf]
version = "0.3.0"
git = "https://github.com/gtk-rs/gdk-pixbuf"

[dependencies.gio]
version = "0.3.0"
git = "https://github.com/gtk-rs/gio"