[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.9"
cairo-sys-rs = "0.4.0"
gdk-pixbuf-sys = "0.4.0"
gdk-sys = "0.4.0"
gio-sys = "0.4.0"
glib-sys = "0.4.0"
gobject-sys = "0.4.0"
gtk-sys = "0.4.0"
libc = "0.2"

[features]
v3_10 = ["v3_8"]
v3_12 = ["v3_10"]
v3_14 = ["v3_12"]
v3_16 = ["v3_14"]
v3_18 = ["v3_16"]
v3_20 = ["v3_18"]
v3_4 = []
v3_8 = ["v3_4"]

[lib]
name = "gtk_source_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgtksourceview-3"
homepage = "http://gtk-rs.org/"
keywords = ["gtk", "ffi", "gtk-rs", "gnome", "sourceview"]
license = "MIT"
links = "gtk_source"
name = "gtk-source-sys"
repository = "https://github.com/gtk-rs/sourceview"
version = "0.4.2"
