[options]
girs_dir = "../gir-files"
library = "GtkSource"
version = "3.0"
min_cfg_version = "3.0"
target_path = "."
work_mode = "sys"
single_version_file = "."

external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "Gtk",
   "GdkPixbuf",
   "Gdk",
   "Cairo",
]

ignore = [
]
